// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7L0VaVsRCR7vNbi8vozLvdaQPADtEQRo',
    appId: '1:452965143565:web:92d034e396eeac1bb47144',
    messagingSenderId: '452965143565',
    projectId: 'laundryv2-54520',
    authDomain: 'laundryv2-54520.firebaseapp.com',
    storageBucket: 'laundryv2-54520.firebasestorage.app',
    measurementId: 'G-DSJ9ZJDF57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUIIBtQx0A2W-ZZMoXImzOns4-2AM96A',
    appId: '1:452965143565:android:a8451e45eebe8ca2b47144',
    messagingSenderId: '452965143565',
    projectId: 'laundryv2-54520',
    storageBucket: 'laundryv2-54520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKx5kH0AzhPB6ID66fraxcMXITJ25Kbc',
    appId: '1:452965143565:ios:5e241724356d4d5ab47144',
    messagingSenderId: '452965143565',
    projectId: 'laundryv2-54520',
    storageBucket: 'laundryv2-54520.firebasestorage.app',
    iosBundleId: 'com.example.laundryv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKx5kH0AzhPB6ID66fraxcMXITJ25Kbc',
    appId: '1:452965143565:ios:5e241724356d4d5ab47144',
    messagingSenderId: '452965143565',
    projectId: 'laundryv2-54520',
    storageBucket: 'laundryv2-54520.firebasestorage.app',
    iosBundleId: 'com.example.laundryv2',
  );

}